version: '3.7'

services:
  storage_pg:
    image: postgres:13
    container_name: storage_pg
    hostname: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresdoc
      POSTGRES_DB: coinmarketcap
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  airflow:
    image: apache/airflow:2.5.0
    container_name: airflow
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@storage_pg:5432/coinmarketcap
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - 8080:8080
    depends_on:
      storage_pg:
        condition: service_healthy
    restart: always

  webserver:
    image: apache/airflow:2.5.0
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
    restart: always
    depends_on:
      - storage_pg
      - airflow

  scheduler:
    image: apache/airflow:2.5.0
    container_name: airflow_scheduler
    command: scheduler
    environment:
      - EXECUTOR=LocalExecutor
    restart: always
    depends_on:
      - webserver
